name: Test Bot-Created Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release (e.g., v1.0.0)"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.version }} --title "Release ${{ inputs.version }}" --notes "Automatically created by workflow."
