name: Enforce Bot-Created Releases only

on:
  release:
    types:
      - created

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Delete the release and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting tag: ${{ github.event.release.tag_name }}"
          git tag -d ${{ github.event.release.tag_name }}
          git push origin --delete ${{ github.event.release.tag_name }}

      - name: Fail the action with a descriptive message
        run: |
          echo "Error: Manually triggered releases are not allowed."
          exit 1
