name: Delete manually created release

on:
  release:
    types:
      - created

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Delete the release associated with the created tag
      - name: Delete Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting release: ${{ github.event.release.tag_name }}"
          gh release delete ${{ github.event.release.tag_name }} --yes

      - name: Delete the release and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting tag: ${{ github.event.release.tag_name }}"
          git tag -d ${{ github.event.release.tag_name }}
          git push origin --delete ${{ github.event.release.tag_name }}

      - name: Why was this release deleted?
        run: |
          echo "Error: Manually triggered releases are not allowed."
          exit 0
