name: Update PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Hello World'
          direction: last

      - name: Create or Update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Hello World V3
            This comment was last updated at: ${{ github.event.pull_request.updated_at }}
          edit-mode: replace
